version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - PGDATA=/var/lib/postgresql/data/pgdata
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-priority
    ports:
      - 7000:7000
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST=db
    restart: always
    depends_on:
      - db
    volumes:
      - .:/opt/server/
      - /opt/server/node_modules
  nginx:
    image: nginx:1.17.8-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 8989:8989
